### ISSUE TITLE
04.03.2020 - Stand Up meeting

### ISSUE THREAD

**Issue by AdedayoOpeyemi** [lBuggie/the-next-web#1]
#Create Master branch

**Comment by SevlaMare** [comment]
device-width is deprecated, see more in: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries.
You can use something like: @media (min-width: 768px) and (max-width: 1023px)  to setup the queries for work in a range of widths.

**Comment by idgm5** [comment]
Yes, we will create the master branch once the project is finished. 

Thank you for your observation! :)
