### ISSUE TITLE
05/03 - Code Review #Team94

### ISSUE THREAD

**Issue by idgm5** [lBuggie/the-next-web#2]
Any suggestions or comments please post them here

**Comment by SevlaMare** [comment]
device-width is deprecated, see more in: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries.
You can use something like: @media (min-width: 768px) and (max-width: 1023px) to setup the queries to work in a range of widths.

**Comment by sebGilR** [comment]
Issue has been fixed.
